# Generated by Django 4.2.7 on 2025-11-07 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del envío')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('estimated_days', models.CharField(max_length=50, verbose_name='Días estimados')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('is_active', models.BooleanField(default=True, verbose_name='Activo')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Zona')),
                ('postal_code_start', models.CharField(max_length=10, verbose_name='Código postal inicio')),
                ('postal_code_end', models.CharField(max_length=10, verbose_name='Código postal fin')),
                ('shipping_option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.shippingoption')),
            ],
        ),
    ]
