# Generated by Django 5.2.8 on 2025-11-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_alter_order_options_alter_orderitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Imagen principal del producto', null=True, upload_to='products/', verbose_name='Imagen'),
        ),
    ]
